name: Commits and Pull Requests
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    name: Run Unit tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build
        run: bash ./gradlew build
  instrumentation-test:
    name: Run Instrumentation tests
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make files executable
        run: chmod +x ./gradlew
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: pixel
          target: google_apis
          script: ./gradlew connectedCheck
  screenshot-test:
    name: Run Screenshot tests
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make files executable
        run: chmod +x ./gradlew
      - name: Screenshot tests
        uses: reactivecircus/android-emulator-runner@v2.24.0
        with:
          api-level: 31
          arch: x86_64
          profile: pixel
          target: google_apis
          sdcard-path-or-size: 512M
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script: ./gradlew executeScreenshotTests -Pandroid.testInstrumentationRunnerArguments.size=medium