name: Commits and Pull Requests

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  unit-tests:
    name: Run Unit tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/tests/

  instrumentation-test:
    name: Run Instrumentation tests
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Make files executable
        run: chmod +x ./gradlew
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck