name: Commits and Pull Requests
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  unit-tests:
    name: Run Unit tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Unit tests
        run: bash ./gradlew test
  instrumentation-test:
    name: Run Instrumentation tests
    runs-on: macos-latest
    steps:
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: checkout
        uses: actions/checkout@v3
      - name: Make files executable
        run: chmod +x ./gradlew
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: Pixel 5
          script: ./gradlew connectedCheck
  screenshot-test:
    name: Run Screenshot tests
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Make files executable
        run: chmod +x ./gradlew
      - name: Screenshot tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: Pixel 5
          script: ./gradlew executeScreenshotTests -Pandroid.testInstrumentationRunnerArguments.size=medium